name: Rocket
main: shamebot.rocket.Rocket
version: 0.6
author: Shamebot
description: Launches a player into space.
commands:
    launch:
     description: Launches a player into space.
     usage:
         /<command> <duration> [playername|entityId]
    launcher:
     description: Enables launcher mode.
     usage:
         /<command> <duration>
    halt:
     description: Stops acceleration.
     usage:
         /<command> [playername|entityId]
    shoot:
     description: Shoots a player in the direction you're facing.
     usage:
         /<command> <duration> [playername|entityId]
    shooter:
     description: Enables shooter mode.
     usage:
         /<command> <duration>
    fly:
     description: Use left + rightclick to fly
     usage:
         /<command> <strength> [playername|entityId]
    rkick:
     description: Launches a player and kicks him
     usage:
         /<command> <strength> [playername|entityId]